/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Pulverizacao } from "./Pulverizacao";
import { PulverizacaoCountArgs } from "./PulverizacaoCountArgs";
import { PulverizacaoFindManyArgs } from "./PulverizacaoFindManyArgs";
import { PulverizacaoFindUniqueArgs } from "./PulverizacaoFindUniqueArgs";
import { DeletePulverizacaoArgs } from "./DeletePulverizacaoArgs";
import { PulverizacaoService } from "../pulverizacao.service";
@graphql.Resolver(() => Pulverizacao)
export class PulverizacaoResolverBase {
  constructor(protected readonly service: PulverizacaoService) {}

  async _pulverizacaosMeta(
    @graphql.Args() args: PulverizacaoCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Pulverizacao])
  async pulverizacaos(
    @graphql.Args() args: PulverizacaoFindManyArgs
  ): Promise<Pulverizacao[]> {
    return this.service.pulverizacaos(args);
  }

  @graphql.Query(() => Pulverizacao, { nullable: true })
  async pulverizacao(
    @graphql.Args() args: PulverizacaoFindUniqueArgs
  ): Promise<Pulverizacao | null> {
    const result = await this.service.pulverizacao(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Pulverizacao)
  async deletePulverizacao(
    @graphql.Args() args: DeletePulverizacaoArgs
  ): Promise<Pulverizacao | null> {
    try {
      return await this.service.deletePulverizacao(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
