/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AreaService } from "../area.service";
import { AreaCreateInput } from "./AreaCreateInput";
import { Area } from "./Area";
import { AreaFindManyArgs } from "./AreaFindManyArgs";
import { AreaWhereUniqueInput } from "./AreaWhereUniqueInput";
import { AreaUpdateInput } from "./AreaUpdateInput";

export class AreaControllerBase {
  constructor(protected readonly service: AreaService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Area })
  async createArea(@common.Body() data: AreaCreateInput): Promise<Area> {
    return await this.service.createArea({
      data: data,
      select: {
        createdAt: true,
        fazenda: true,
        id: true,
        nome: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Area] })
  @ApiNestedQuery(AreaFindManyArgs)
  async areas(@common.Req() request: Request): Promise<Area[]> {
    const args = plainToClass(AreaFindManyArgs, request.query);
    return this.service.areas({
      ...args,
      select: {
        createdAt: true,
        fazenda: true,
        id: true,
        nome: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Area })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async area(
    @common.Param() params: AreaWhereUniqueInput
  ): Promise<Area | null> {
    const result = await this.service.area({
      where: params,
      select: {
        createdAt: true,
        fazenda: true,
        id: true,
        nome: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Area })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateArea(
    @common.Param() params: AreaWhereUniqueInput,
    @common.Body() data: AreaUpdateInput
  ): Promise<Area | null> {
    try {
      return await this.service.updateArea({
        where: params,
        data: data,
        select: {
          createdAt: true,
          fazenda: true,
          id: true,
          nome: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Area })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteArea(
    @common.Param() params: AreaWhereUniqueInput
  ): Promise<Area | null> {
    try {
      return await this.service.deleteArea({
        where: params,
        select: {
          createdAt: true,
          fazenda: true,
          id: true,
          nome: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
